package com.lancer.passwordhelper.model.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lancer.passwordhelper.bean.Card;
import com.lancer.passwordhelper.bean.Category;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig categoryDaoConfig;

    private final CardDao cardDao;
    private final CategoryDao categoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(Category.class, categoryDao);
    }
    
    public void clear() {
        cardDaoConfig.clearIdentityScope();
        categoryDaoConfig.clearIdentityScope();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

}
